### ISSUE TITLE
Error: Object 'path' Not Found When Saving Model in R Script

### ISSUE THREAD

**Issue by Gos2two** [yass-78/Osteoporosis-Risk-Prediction#1]
Hello,

I encountered an issue when running the following line of code in the file Treball_Final_BIoinfo.R:

`save(model, file = paste0(path, "logistic_model.RData"))`

I received the following error:

`Error: object 'path' not found`

Could you help me understand what might be causing this error and how to resolve it?

Thank you!

**Comment by yass-78** [comment]
Hello,

Thank you for pointing out the issue. The error happens because the variable path is not defined in the script. To fix this, you can remove path from the save function and use the file name directly. Here’s the corrected code:

```
save(model, file = "logistic_model.RData")

save(modelRF, file = "random_forest_model.RData")
```

Let me know if you have further questions!

**Comment by Gos2two** [comment]
Thank you @yass-78 , I have now tested your proposed solution and it works for me!
